name: NekoWorldRegen
main: jp.kentan.minecraft.neko_world_regen.NekoWorldRegen
version: 1.2.5
author: ken_kentan
website: http://ken.kentan.jp
depend: [Multiverse-Core]
softdepend: [WorldGuard, FastAsyncWorldEdit]

commands:
    regen:
        description: NekoWorldRegen
        usage: /<command>
        permission: neko.regen
        permission-message: You don't have <permission>